name: atotp_server
description: Comand-like application to generate OTP codes on server.
version: 1.0.0
homepage: https://github.com/ch-cheer
repository: https://github.com/ch-cheer/ATOTP-server
documentation: https://github.com/ch-cheer/ATOTP-server/documentation
issue_tracker: https://github.com/ch-cheer/ATOTP-server/issues

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  crypto: ^3.0.7
  base32: ^2.2.0
  args: ^2.7.0
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: 
  assets:
    - .env

platforms:
  windows:
  linux:
  macos: